version: "3.9"

services:
  flux_app:
    build: .
    container_name: flux_container
    # Enable GPU access (requires Docker >= 19.03 and NVIDIA Container Toolkit)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      HF_TOKEN: ${HF_TOKEN}  # Will be read from your local .env file or shell
    volumes:
      - ./output:/app/output  
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - ./config:/app/config
    command: ["python", "run.py", "./config/examples/train_lora_flux_24gb.yaml", "--log", "./flux.log"]



 