version: "3.8"

services:
  ai-toolkit:
    image: ostris/aitoolkit:latest
    restart: unless-stopped
    ports:
      - "8675:8675"

    environment:

      - NODE_ENV=production
      - TZ=UTC
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all



 
